<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ElementsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {

        $periodic_table = [
            [
                'mass' => 1.008,
                'neutron' => 0,
                'name' => 'Hydrogène',
                'slug' => 'hydrogene',
                'symbol' => 'H',
                'period' => 1,
                'group' => 1,
                'distribution' => '1',
                'state' => 1,
                'family' => 10,
                'occurence' => 'Primordial',
            ],

            [
                'mass' => 4.002602,
                'neutron' => 2,
                'name' => 'Hélium',
                'slug' => 'helium',
                'symbol' => 'He',
                'period' => 1,
                'group' => 18,
                'distribution' => '2',
                'state' => 1,
                'family' => 4,
                'occurence' => 'Primordial',
            ],

            [
                'mass' => 6.94,
                'neutron' => 4,
                'name' => 'Lithium',
                'slug' => 'lithium',
                'symbol' => 'Li',
                'period' => 2,
                'group' => 1,
                'distribution' => '2,1',
                'state' => 3,
                'family' => 2,
                'occurence' => 'Primordial',
            ],

            [
                'mass' => 9.012182,
                'neutron' => 5,
                'name' => 'Béryllium',
                'slug' => 'beryllium',
                'symbol' => 'Be',
                'period' => 2,
                'group' => 2,
                'distribution' => '2,2',
                'state' => 3,
                'family' => 3,
                'occurence' => 'Primordial',
            ],

            [
                'mass' => 10.81,
                'neutron' => 5,
                'name' => 'Bore',
                'slug' => 'bore',
                'symbol' => 'B',
                'period' => 2,
                'group' => 13,
                'distribution' => '2,3',
                'state' => 3,
                'family' => 7,
                'occurence' => 'Primordial',
            ],

            [
                'mass' => 12.011,
                'neutron' => 6,
                'name' => 'Carbone',
                'slug' => 'carbone',
                'symbol' => 'C',
                'period' => 2,
                'group' => 14,
                'distribution' => '2,4',
                'state' => 3,
                'family' => 10,
                'occurence' => 'Primordial',
            ],

            [
                'mass' => 14.007,
                'neutron' => 7,
                'name' => 'Azote',
                'slug' => 'azote',
                'symbol' => 'N',
                'period' => 2,
                'group' => 15,
                'distribution' => '2,5',
                'state' => 1,
                'family' => 10,
                'occurence' => 'Primordial',
            ],

            [
                'mass' => 15.999,
                'neutron' => 8,
                'name' => 'Oxygène',
                'slug' => 'oxygene',
                'symbol' => 'O',
                'period' => 2,
                'group' => 16,
                'distribution' => '2,6',
                'state' => 1,
                'family' => 10,
                'occurence' => 'Primordial',
            ],

            [
                'mass' => 18.9984032,
                'neutron' => 10,
                'name' => 'Fluor',
                'slug' => 'fluor',
                'symbol' => 'F',
                'period' => 2,
                'group' => 17,
                'distribution' => '2,7',
                'state' => 1,
                'family' => 5,
                'occurence' => 'Primordial',
            ],

            [
                'mass' => 20.1797,
                'neutron' => 5,
                'name' => 'Néon',
                'slug' => 'neon',
                'symbol' => 'Ne',
                'period' => 2,
                'group' => 18,
                'distribution' => '2,8',
                'state' => 1,
                'family' => 4,
                'occurence' => 'Primordial',
            ],

            [
                'mass' => 22.98976928,
                'neutron' => 12,
                'name' => 'Sodium',
                'slug' => 'sodium',
                'symbol' => 'Na',
                'period' => 3,
                'group' => 1,
                'distribution' => '2,8,1',
                'state' => 3,
                'family' => 2,
                'occurence' => 'Primordial',
            ],

            [
                'mass' => 24.305,
                'neutron' => 12,
                'name' => 'Magnésium',
                'slug' => 'magnesium',
                'symbol' => 'Mg',
                'period' => 3,
                'group' => 2,
                'distribution' => '2,8,2',
                'state' => 3,
                'family' => 3,
                'occurence' => 'Primordial',
            ],

            [
                'mass' => 26.9815386,
                'neutron' => 14,
                'name' => 'Aluminium',
                'slug' => 'aluminium',
                'symbol' => 'Al',
                'period' => 3,
                'group' => 13,
                'distribution' => '2,8,3',
                'state' => 3,
                'family' => 9,
                'occurence' => 'Primordial',
            ],

            [
                'mass' => 28.085,
                'neutron' => 14,
                'name' => 'Silicium',
                'slug' => 'silicium',
                'symbol' => 'Si',
                'period' => 3,
                'group' => 14,
                'distribution' => '2,8,4',
                'state' => 3,
                'family' => 7,
                'occurence' => 'Primordial',
            ],

            [
                'mass' => 30.974,
                'neutron' => 16,
                'name' => 'Phosphore',
                'slug' => 'phosphore',
                'symbol' => 'P',
                'period' => 3,
                'group' => 15,
                'distribution' => '2,8,5',
                'state' => 3,
                'family' => 10,
                'occurence' => 'Primordial',
            ],

            [
                'mass' => 32.06,
                'neutron' => 16,
                'name' => 'Soufre',
                'slug' => 'soufre',
                'symbol' => 'S',
                'period' => 3,
                'group' => 16,
                'distribution' => '2,8,6',
                'state' => 3,
                'family' => 10,
                'occurence' => 'Primordial',
            ],

            [
                'mass' => 35.45,
                'neutron' => 18,
                'name' => 'Chlore',
                'slug' => 'chlore',
                'symbol' => 'Cl',
                'period' => 3,
                'group' => 17,
                'distribution' => '2,8,7',
                'state' => 1,
                'family' => 5,
                'occurence' => 'Primordial',
            ],

            [
                'mass' => 39.948,
                'neutron' => 22,
                'name' => 'Argon',
                'slug' => 'argon',
                'symbol' => 'Ar',
                'period' => 3,
                'group' => 18,
                'distribution' => '2,8,8',
                'state' => 1,
                'family' => 4,
                'occurence' => 'Primordial',
            ],

            [
                'mass' => 39.0983,
                'neutron' => 20,
                'name' => 'Potassium',
                'slug' => 'potassium',
                'symbol' => 'K',
                'period' => 4,
                'group' => 1,
                'distribution' => '2,8,8,1',
                'state' => 3,
                'family' => 2,
                'occurence' => 'Primordial',
            ],

            [
                'mass' => 40.078,
                'neutron' => 20,
                'name' => 'Calcium',
                'slug' => 'calcium',
                'symbol' => 'Ca',
                'period' => 4,
                'group' => 2,
                'distribution' => '2,8,8,2',
                'state' => 3,
                'family' => 3,
                'occurence' => 'Primordial',
            ],

            [
                'mass' => 44.955912,
                'neutron' => 24,
                'name' => 'Scandium',
                'slug' => 'scandium',
                'symbol' => 'Sc',
                'period' => 4,
                'group' => 3,
                'distribution' => '2,8,9,2',
                'state' => 3,
                'family' => 8,
                'occurence' => 'Primordial',
            ],

            [
                'mass' => 47.867,
                'neutron' => 26,
                'name' => 'Titane',
                'slug' => 'titane',
                'symbol' => 'Ti',
                'period' => 4,
                'group' => 4,
                'distribution' => '2,8,10,2',
                'state' => 3,
                'family' => 8,
                'occurence' => 'Primordial',
            ],

            [
                'mass' => 50.9415,
                'neutron' => 28,
                'name' => 'Vanadium',
                'slug' => 'vanadium',
                'symbol' => 'V',
                'period' => 4,
                'group' => 5,
                'distribution' => '2,8,11,2',
                'state' => 3,
                'family' => 8,
                'occurence' => 'Primordial',
            ],

            [
                'mass' => 51.9961,
                'neutron' => 28,
                'name' => 'Chrome',
                'slug' => 'chrome',
                'symbol' => 'Cr',
                'period' => 4,
                'group' => 6,
                'distribution' => '2,8,13,1',
                'state' => 3,
                'family' => 8,
                'occurence' => 'Primordial',
            ],

            [
                'mass' => 54.938045,
                'neutron' => 30,
                'name' => 'Manganèse',
                'slug' => 'manganese',
                'symbol' => 'Mn',
                'period' => 4,
                'group' => 7,
                'distribution' => '2,8,13,2',
                'state' => 3,
                'family' => 8,
                'occurence' => 'Primordial',
            ],

            [
                'mass' => 55.845,
                'neutron' => 30,
                'name' => 'Fer',
                'slug' => 'fer',
                'symbol' => 'Fe',
                'period' => 4,
                'group' => 8,
                'distribution' => '2,8,14,2',
                'state' => 3,
                'family' => 8,
                'occurence' => 'Primordial',
            ],

            [
                'mass' => 58.933195,
                'neutron' => 32,
                'name' => 'Cobalt',
                'slug' => 'cobalt',
                'symbol' => 'Co',
                'period' => 4,
                'group' => 9,
                'distribution' => '2,8,15,2',
                'state' => 3,
                'family' => 8,
                'occurence' => 'Primordial',
            ],

            [
                'mass' => 58.6934,
                'neutron' => 31,
                'name' => 'Nickel',
                'slug' => 'nickel',
                'symbol' => 'Ni',
                'period' => 4,
                'group' => 10,
                'distribution' => '2,8,16,2',
                'state' => 3,
                'family' => 8,
                'occurence' => 'Primordial',
            ],

            [
                'mass' => 63.546,
                'neutron' => 35,
                'name' => 'Cuivre',
                'slug' => 'cuivre',
                'symbol' => 'Cu',
                'period' => 4,
                'group' => 11,
                'distribution' => '2,8,18,1',
                'state' => 3,
                'family' => 8,
                'occurence' => 'Primordial',
            ],

            [
                'mass' => 65.38,
                'neutron' => 35,
                'name' => 'Zinc',
                'slug' => 'zinc',
                'symbol' => 'Zn',
                'period' => 4,
                'group' => 12,
                'distribution' => '2,8,18,2',
                'state' => 3,
                'family' => 9,
                'occurence' => 'Primordial',
            ],

            [
                'mass' => 69.723,
                'neutron' => 39,
                'name' => 'Gallium',
                'slug' => 'gallium',
                'symbol' => 'Ga',
                'period' => 4,
                'group' => 13,
                'distribution' => '2,8,18,3',
                'state' => 3,
                'family' => 9,
                'occurence' => 'Primordial',
            ],

            [
                'mass' => 72.63,
                'neutron' => 41,
                'name' => 'Germanium',
                'slug' => 'germanium',
                'symbol' => 'Ge',
                'period' => 4,
                'group' => 14,
                'distribution' => '2,8,18,4',
                'state' => 3,
                'family' => 7,
                'occurence' => 'Primordial',
            ],

            [
                'mass' => 74.92160,
                'neutron' => 42,
                'name' => 'Arsenic',
                'slug' => 'arsenic',
                'symbol' => 'As',
                'period' => 4,
                'group' => 15,
                'distribution' => '2,8,18,5',
                'state' => 3,
                'family' => 7,
                'occurence' => 'Primordial',
            ],

            [
                'mass' => 79.96,
                'neutron' => 46,
                'name' => 'Sélénium',
                'slug' => 'selenium',
                'symbol' => 'Se',
                'period' => 4,
                'group' => 16,
                'distribution' => '2,8,18,6',
                'state' => 3,
                'family' => 10,
                'occurence' => 'Primordial',
            ],

            [
                'mass' => 79.904,
                'neutron' => 45,
                'name' => 'Brome',
                'slug' => 'brome',
                'symbol' => 'Br',
                'period' => 4,
                'group' => 17,
                'distribution' => '2,8,18,7',
                'state' => 2,
                'family' => 5,
                'occurence' => 'Primordial',
            ],

            [
                'mass' => 83.798,
                'neutron' => 48,
                'name' => 'Krypton',
                'slug' => 'krypton',
                'symbol' => 'Kr',
                'period' => 4,
                'group' => 18,
                'distribution' => '2,8,18,8',
                'state' => 1,
                'family' => 4,
                'occurence' => 'Primordial',
            ],

            [
                'mass' => 85.4678,
                'neutron' => 49,
                'name' => 'Rubidium',
                'slug' => 'rubidium',
                'symbol' => 'Rb',
                'period' => 5,
                'group' => 1,
                'distribution' => '2,8,18,8,1',
                'state' => 3,
                'family' => 2,
                'occurence' => 'Primordial',
            ],

            [
                'mass' => 87.62,
                'neutron' => 50,
                'name' => 'Strontium',
                'slug' => 'strontium',
                'symbol' => 'Sr',
                'period' => 5,
                'group' => 2,
                'distribution' => '2,8,18,8,2',
                'state' => 3,
                'family' => 3,
                'occurence' => 'Primordial',
            ],

            [
                'mass' => 88.90585,
                'neutron' => 51,
                'name' => 'Yttrium',
                'slug' => 'yttrium',
                'symbol' => 'Y',
                'period' => 5,
                'group' => 3,
                'distribution' => '2,8,18,9,2',
                'state' => 3,
                'family' => 8,
                'occurence' => 'Primordial',
            ],

            [
                'mass' => 91.224,
                'neutron' => 51,
                'name' => 'Zirconium',
                'slug' => 'zirconium',
                'symbol' => 'Zr',
                'period' => 5,
                'group' => 4,
                'distribution' => '2,8,18,10,2',
                'state' => 3,
                'family' => 8,
                'occurence' => 'Primordial',
            ],

            [
                'mass' => 92.90638,
                'neutron' => 52,
                'name' => 'Niobium',
                'slug' => 'niobium',
                'symbol' => 'Nb',
                'period' => 5,
                'group' => 5,
                'distribution' => '2,8,18,12,1',
                'state' => 3,
                'family' => 8,
                'occurence' => 'Primordial',
            ],

            [
                'mass' => 95.96,
                'neutron' => 54,
                'name' => 'Molybdène',
                'slug' => 'molybdene',
                'symbol' => 'Mo',
                'period' => 5,
                'group' => 6,
                'distribution' => '2,8,18,13,1',
                'state' => 3,
                'family' => 8,
                'occurence' => 'Primordial',
            ],

            [
                'mass' => 98,
                'neutron' => 55,
                'name' => 'Technétium',
                'slug' => 'technetium',
                'symbol' => 'Tc',
                'period' => 5,
                'group' => 7,
                'distribution' => '2,8,18,13,2',
                'state' => 3,
                'family' => 8,
                'occurence' => 'Radioactif',
            ],

            [
                'mass' => 101.07,
                'neutron' => 57,
                'name' => 'Ruthénium',
                'slug' => 'ruthenium',
                'symbol' => 'Ru',
                'period' => 5,
                'group' => 8,
                'distribution' => '2,8,18,15,1',
                'state' => 3,
                'family' => 8,
                'occurence' => 'Primordial',
            ],

            [
                'mass' => 102.90550,
                'neutron' => 58,
                'name' => 'Rhodium',
                'slug' => 'rhodium',
                'symbol' => 'Rh',
                'period' => 5,
                'group' => 9,
                'distribution' => '2,8,18,16,1',
                'state' => 3,
                'family' => 8,
                'occurence' => 'Primordial',
            ],

            [
                'mass' => 106.42,
                'neutron' => 60,
                'name' => 'Palladium',
                'slug' => 'palladium',
                'symbol' => 'Pd',
                'period' => 5,
                'group' => 10,
                'distribution' => '2,8,18,18,0',
                'state' => 3,
                'family' => 8,
                'occurence' => 'Primordial',
            ],

            [
                'mass' => 107.8682,
                'neutron' => 61,
                'name' => 'Argent',
                'slug' => 'argent',
                'symbol' => 'Ag',
                'period' => 5,
                'group' => 11,
                'distribution' => '2,8,18,18,1',
                'state' => 3,
                'family' => 8,
                'occurence' => 'Primordial',
            ],

            [
                'mass' => 112.411,
                'neutron' => 64,
                'name' => 'Cadmium',
                'slug' => 'cadmium',
                'symbol' => 'Cd',
                'period' => 5,
                'group' => 12,
                'distribution' => '2,8,18,18,2',
                'state' => 3,
                'family' => 9,
                'occurence' => 'Primordial',
            ],

            [
                'mass' => 114.818,
                'neutron' => 66,
                'name' => 'Indium',
                'slug' => 'indium',
                'symbol' => 'In',
                'period' => 5,
                'group' => 13,
                'distribution' => '2,8,18,18,3',
                'state' => 3,
                'family' => 9,
                'occurence' => 'Primordial',
            ],

            [
                'mass' => 118.710,
                'neutron' => 69,
                'name' => 'Étain',
                'slug' => 'etain',
                'symbol' => 'Sn',
                'period' => 5,
                'group' => 14,
                'distribution' => '2,8,18,18,4',
                'state' => 3,
                'family' => 9,
                'occurence' => 'Primordial',
            ],

            [
                'mass' => 121.760,
                'neutron' => 71,
                'name' => 'Antimoine',
                'slug' => 'antimoine',
                'symbol' => 'Sb',
                'period' => 5,
                'group' => 15,
                'distribution' => '2,8,18,18,5',
                'state' => 3,
                'family' => 7,
                'occurence' => 'Primordial',
            ],

            [
                'mass' => 127.60,
                'neutron' => 76,
                'name' => 'Tellure',
                'slug' => 'tellure',
                'symbol' => 'Te',
                'period' => 5,
                'group' => 16,
                'distribution' => '2,8,18,18,6',
                'state' => 3,
                'family' => 7,
                'occurence' => 'Primordial',
            ],

            [
                'mass' => 126.90447,
                'neutron' => 74,
                'name' => 'Iode',
                'slug' => 'iode',
                'symbol' => 'I',
                'period' => 5,
                'group' => 17,
                'distribution' => '2,8,18,18,7',
                'state' => 3,
                'family' => 5,
                'occurence' => 'Primordial',
            ],

            [
                'mass' => 131.293,
                'neutron' => 77,
                'name' => 'Xénon',
                'slug' => 'xenon',
                'symbol' => 'Xe',
                'period' => 5,
                'group' => 18,
                'distribution' => '2,8,18,18,8',
                'state' => 1,
                'family' => 4,
                'occurence' => 'Primordial',
            ],

            [
                'mass' => 132.9054519,
                'neutron' => 78,
                'name' => 'Césium',
                'slug' => 'cesium',
                'symbol' => 'Cs',
                'period' => 6,
                'group' => 1,
                'distribution' => '2,8,18,18,8,1',
                'state' => 3,
                'family' => 2,
                'occurence' => 'Primordial',
            ],

            [
                'mass' => 137.327,
                'neutron' => 81,
                'name' => 'Baryum',
                'slug' => 'baryum',
                'symbol' => 'Ba',
                'period' => 6,
                'group' => 2,
                'distribution' => '2,8,18,18,8,2',
                'state' => 3,
                'family' => 3,
                'occurence' => 'Primordial',
            ],

            [
                'mass' => 138.90547,
                'neutron' => 82,
                'name' => 'Lanthane',
                'slug' => 'lanthane',
                'symbol' => 'La',
                'period' => 6,
                'group' => 3,
                'distribution' => '2,8,18,18,9,2',
                'state' => 3,
                'family' => 6,
                'occurence' => 'Primordial',
            ],

            [
                'mass' => 140.116,
                'neutron' => 82,
                'name' => 'Cérium',
                'slug' => 'cerium',
                'symbol' => 'Ce',
                'period' => 6,
                'group' => 3,
                'distribution' => '2,8,18,19,9,2',
                'state' => 3,
                'family' => 6,
                'occurence' => 'Primordial',
            ],

            [
                'mass' => 140.90765,
                'neutron' => 82,
                'name' => 'Praséodyme',
                'slug' => 'praseodyme',
                'symbol' => 'Pr',
                'period' => 6,
                'group' => 3,
                'distribution' => '2,8,18,21,8,2',
                'state' => 3,
                'family' => 6,
                'occurence' => 'Primordial',
            ],

            [
                'mass' => 144.242,
                'neutron' => 82,
                'name' => 'Néodyme',
                'slug' => 'neodyme',
                'symbol' => 'Nd',
                'period' => 6,
                'group' => 3,
                'distribution' => '2,8,18,22,8,2',
                'state' => 3,
                'family' => 6,
                'occurence' => 'Primordial',
            ],

            [
                'mass' => 145,
                'neutron' => 84,
                'name' => 'Prométhium',
                'slug' => 'promethium',
                'symbol' => 'Pm',
                'period' => 6,
                'group' => 3,
                'distribution' => '2,8,18,23,8,2',
                'state' => 3,
                'family' => 6,
                'occurence' => 'Radioactif',
            ],

            [
                'mass' => 150.36,
                'neutron' => 88,
                'name' => 'Samarium',
                'slug' => 'samarium',
                'symbol' => 'Sm',
                'period' => 6,
                'group' => 3,
                'distribution' => '2,8,18,24,8,2',
                'state' => 3,
                'family' => 6,
                'occurence' => 'Primordial',
            ],

            [
                'mass' => 151.964,
                'neutron' => 89,
                'name' => 'Europium',
                'slug' => 'europium',
                'symbol' => 'Eu',
                'period' => 6,
                'group' => 3,
                'distribution' => '2,8,18,25,8,2',
                'state' => 3,
                'family' => 6,
                'occurence' => 'Primordial',
            ],

            [
                'mass' => 157.25,
                'neutron' => 93,
                'name' => 'Gadolinium',
                'slug' => 'gadolinium',
                'symbol' => 'Gd',
                'period' => 6,
                'group' => 3,
                'distribution' => '2,8,18,25,9,2',
                'state' => 3,
                'family' => 6,
                'occurence' => 'Primordial',
            ],

            [
                'mass' => 158.92535,
                'neutron' => 94,
                'name' => 'Terbium',
                'slug' => 'terbium',
                'symbol' => 'Tb',
                'period' => 6,
                'group' => 3,
                'distribution' => '2,8,18,27,8,2',
                'state' => 3,
                'family' => 6,
                'occurence' => 'Primordial',
            ],

            [
                'mass' => 162.500,
                'neutron' => 97,
                'name' => 'Dysprosium',
                'slug' => 'dysprosium',
                'symbol' => 'Dy',
                'period' => 6,
                'group' => 3,
                'distribution' => '2,8,18,28,8,2',
                'state' => 3,
                'family' => 6,
                'occurence' => 'Primordial',
            ],

            [
                'mass' => 164.93032,
                'neutron' => 98,
                'name' => 'Holmium',
                'slug' => 'holmium',
                'symbol' => 'Ho',
                'period' => 6,
                'group' => 3,
                'distribution' => '2,8,18,29,8,2',
                'state' => 3,
                'family' => 6,
                'occurence' => 'Primordial',
            ],

            [
                'mass' => 167.259,
                'neutron' => 99,
                'name' => 'Erbium',
                'slug' => 'erbium',
                'symbol' => 'Er',
                'period' => 6,
                'group' => 3,
                'distribution' => '2,8,18,30,8,2',
                'state' => 3,
                'family' => 6,
                'occurence' => 'Primordial',
            ],

            [
                'mass' => 168.93421,
                'neutron' => 100,
                'name' => 'Thulium',
                'slug' => 'thulium',
                'symbol' => 'Tm',
                'period' => 6,
                'group' => 3,
                'distribution' => '2,8,18,31,8,2',
                'state' => 3,
                'family' => 6,
                'occurence' => 'Primordial',
            ],

            [
                'mass' => 173.054,
                'neutron' => 103,
                'name' => 'Ytterbium',
                'slug' => 'ytterbium',
                'symbol' => 'Yb',
                'period' => 6,
                'group' => 3,
                'distribution' => '2,8,18,32,8,2',
                'state' => 3,
                'family' => 6,
                'occurence' => 'Primordial',
            ],

            [
                'mass' => 174.9668,
                'neutron' => 104,
                'name' => 'Lutécium',
                'slug' => 'lutécium',
                'symbol' => 'Lu',
                'period' => 6,
                'group' => 3,
                'distribution' => '2,8,18,32,9,2',
                'state' => 3,
                'family' => 6,
                'occurence' => 'Primordial',
            ],

            [
                'mass' => 178.49,
                'neutron' => 107,
                'name' => 'Hafnium',
                'slug' => 'hafnium',
                'symbol' => 'Hf',
                'period' => 6,
                'group' => 4,
                'distribution' => '2,8,18,32,10,2',
                'state' => 3,
                'family' => 8,
                'occurence' => 'Primordial',
            ],

            [
                'mass' => 180.94788,
                'neutron' => 108,
                'name' => 'Tantale',
                'slug' => 'tantale',
                'symbol' => 'Ta',
                'period' => 6,
                'group' => 5,
                'distribution' => '2,8,18,32,11,2',
                'state' => 3,
                'family' => 8,
                'occurence' => 'Primordial',
            ],

            [
                'mass' => 183.84,
                'neutron' => 110,
                'name' => 'Tungstène',
                'slug' => 'tungstene',
                'symbol' => 'W',
                'period' => 6,
                'group' => 6,
                'distribution' => '2,8,18,32,12,2',
                'state' => 3,
                'family' => 8,
                'occurence' => 'Primordial',
            ],

            [
                'mass' => 186.207,
                'neutron' => 111,
                'name' => 'Rhénium',
                'slug' => 'rhenium',
                'symbol' => 'Re',
                'period' => 6,
                'group' => 7,
                'distribution' => '2,8,18,32,13,2',
                'state' => 3,
                'family' => 8,
                'occurence' => 'Primordial',
            ],

            [
                'mass' => 190.23,
                'neutron' => 114,
                'name' => 'Osmium',
                'slug' => 'osmium',
                'symbol' => 'Os',
                'period' => 6,
                'group' => 8,
                'distribution' => '2,8,18,32,14,2',
                'state' => 3,
                'family' => 8,
                'occurence' => 'Primordial',
            ],

            [
                'mass' => 192.217,
                'neutron' => 115,
                'name' => 'Iridium',
                'slug' => 'iridium',
                'symbol' => 'Ir',
                'period' => 6,
                'group' => 9,
                'distribution' => '2,8,18,32,15,2',
                'state' => 3,
                'family' => 8,
                'occurence' => 'Primordial',
            ],

            [
                'mass' => 195.084,
                'neutron' => 117,
                'name' => 'Platine',
                'slug' => 'platine',
                'symbol' => 'Pt',
                'period' => 6,
                'group' => 10,
                'distribution' => '2,8,18,32,17,1',
                'state' => 3,
                'family' => 8,
                'occurence' => 'Primordial',
            ],

            [
                'mass' => 196.966569,
                'neutron' => 118,
                'name' => 'Or',
                'slug' => 'or',
                'symbol' => 'Au',
                'period' => 6,
                'group' => 11,
                'distribution' => '2,8,18,32,18,1',
                'state' => 3,
                'family' => 8,
                'occurence' => 'Primordial',
            ],

            [
                'mass' => 200.59,
                'neutron' => 121,
                'name' => 'Mercure',
                'slug' => 'mercure',
                'symbol' => 'Hg',
                'period' => 6,
                'group' => 12,
                'distribution' => '2,8,18,32,18,2',
                'state' => 2,
                'family' => 9,
                'occurence' => 'Primordial',
            ],

            [
                'mass' => 204.38,
                'neutron' => 123,
                'name' => 'Thallium',
                'slug' => 'thallium',
                'symbol' => 'Tl',
                'period' => 6,
                'group' => 13,
                'distribution' => '2,8,18,32,18,3',
                'state' => 3,
                'family' => 9,
                'occurence' => 'Primordial',
            ],

            [
                'mass' => 207.2,
                'neutron' => 125,
                'name' => 'Plomb',
                'slug' => 'plomb',
                'symbol' => 'Pb',
                'period' => 6,
                'group' => 14,
                'distribution' => '2,8,18,32,18,4',
                'state' => 3,
                'family' => 9,
                'occurence' => 'Primordial',
            ],

            [
                'mass' => 208.98040,
                'neutron' => 126,
                'name' => 'Bismuth',
                'slug' => 'bismuth',
                'symbol' => 'Bi',
                'period' => 6,
                'group' => 15,
                'distribution' => '2,8,18,32,18,5',
                'state' => 3,
                'family' => 9,
                'occurence' => 'Radioactif',
            ],

            [
                'mass' => 209,
                'neutron' => 125,
                'name' => 'Polonium',
                'slug' => 'polonium',
                'symbol' => 'Po',
                'period' => 6,
                'group' => 16,
                'distribution' => '2,8,18,32,18,6',
                'state' => 3,
                'family' => 9,
                'occurence' => 'Radioactif',
            ],

            [
                'mass' => 210,
                'neutron' => 125,
                'name' => 'Astate',
                'slug' => 'astate',
                'symbol' => 'At',
                'period' => 6,
                'group' => 17,
                'distribution' => '2,8,18,32,18,7',
                'state' => 3,
                'family' => 7,
                'occurence' => 'Radioactif',
            ],

            [
                'mass' => 222,
                'neutron' => 136,
                'name' => 'Radon',
                'slug' => 'radon',
                'symbol' => 'Rn',
                'period' => 6,
                'group' => 18,
                'distribution' => '2,8,18,32,18,8',
                'state' => 1,
                'family' => 4,
                'occurence' => 'Radioactif',
            ],

            [
                'mass' => 223,
                'neutron' => 136,
                'name' => 'Francium',
                'slug' => 'francium',
                'symbol' => 'Fr',
                'period' => 7,
                'group' => 1,
                'distribution' => '2,8,18,32,18,8,1',
                'state' => 3,
                'family' => 2,
                'occurence' => 'Radioactif',
            ],

            [
                'mass' => 226,
                'neutron' => 138,
                'name' => 'Radium',
                'slug' => 'radium',
                'symbol' => 'Ra',
                'period' => 7,
                'group' => 2,
                'distribution' => '2,8,18,32,18,8,2',
                'state' => 3,
                'family' => 3,
                'occurence' => 'Radioactif',
            ],

            [
                'mass' => 227,
                'neutron' => 138,
                'name' => 'Actinium',
                'slug' => 'actinium',
                'symbol' => 'Ac',
                'period' => 7,
                'group' => 3,
                'distribution' => '2,8,18,32,18,9,2',
                'state' => 3,
                'family' => 1,
                'occurence' => 'Radioactif',
            ],

            [
                'mass' => 232.03806,
                'neutron' => 142,
                'name' => 'Thorium',
                'slug' => 'thorium',
                'symbol' => 'Th',
                'period' => 7,
                'group' => 3,
                'distribution' => '2,8,18,32,18,10,2',
                'state' => 3,
                'family' => 1,
                'occurence' => 'Primordial',
            ],

            [
                'mass' => 231.03588,
                'neutron' => 140,
                'name' => 'Protactinium',
                'slug' => 'protactinium',
                'symbol' => 'Pa',
                'period' => 7,
                'group' => 3,
                'distribution' => '2,8,18,32,20,9,2',
                'state' => 3,
                'family' => 1,
                'occurence' => 'Radioactif',
            ],

            [
                'mass' => 238.02891,
                'neutron' => 146,
                'name' => 'Uranium',
                'slug' => 'uranium',
                'symbol' => 'U',
                'period' => 7,
                'group' => 3,
                'distribution' => '2,8,18,32,21,9,2',
                'state' => 3,
                'family' => 1,
                'occurence' => 'Primordial',
            ],

            [
                'mass' => 237,
                'neutron' => 144,
                'name' => 'Neptunium',
                'slug' => 'neptunium',
                'symbol' => 'Np',
                'period' => 7,
                'group' => 3,
                'distribution' => '2,8,18,32,22,9,2',
                'state' => 3,
                'family' => 1,
                'occurence' => 'Radioactif',
            ],

            [
                'mass' => 244,
                'neutron' => 150,
                'name' => 'Plutonium',
                'slug' => 'plutonium',
                'symbol' => 'Pu',
                'period' => 7,
                'group' => 3,
                'distribution' => '2,8,18,32,24,8,2',
                'state' => 3,
                'family' => 1,
                'occurence' => 'Primordial',
            ],

            [
                'mass' => 243,
                'neutron' => 148,
                'name' => 'Américium',
                'slug' => 'americium',
                'symbol' => 'Am',
                'period' => 7,
                'group' => 3,
                'distribution' => '2,8,18,32,25,8,2',
                'state' => 3,
                'family' => 1,
                'occurence' => 'Synthétique',
            ],

            [
                'mass' => 247,
                'neutron' => 151,
                'name' => 'Curium',
                'slug' => 'curium',
                'symbol' => 'Cm',
                'period' => 7,
                'group' => 3,
                'distribution' => '2,8,18,32,25,9,2',
                'state' => 3,
                'family' => 1,
                'occurence' => 'Synthétique',
            ],

            [
                'mass' => 247,
                'neutron' => 150,
                'name' => 'Berkélium',
                'slug' => 'berkelium',
                'symbol' => 'Bk',
                'period' => 7,
                'group' => 3,
                'distribution' => '2,8,18,32,27,8,2',
                'state' => 3,
                'family' => 1,
                'occurence' => 'Synthétique',
            ],

            [
                'mass' => 251,
                'neutron' => 153,
                'name' => 'Californium',
                'slug' => 'californium',
                'symbol' => 'Cf',
                'period' => 7,
                'group' => 3,
                'distribution' => '2,8,18,32,28,8,2',
                'state' => 3,
                'family' => 1,
                'occurence' => 'Synthétique',
            ],

            [
                'mass' => 252,
                'neutron' => 153,
                'name' => 'Einsteinium',
                'slug' => 'einsteinium',
                'symbol' => 'Es',
                'period' => 7,
                'group' => 3,
                'distribution' => '2,8,18,32,29,8,2',
                'state' => 3,
                'family' => 1,
                'occurence' => 'Synthétique',
            ],

            [
                'mass' => 257,
                'neutron' => 157,
                'name' => 'Fermium',
                'slug' => 'fermium',
                'symbol' => 'Fm',
                'period' => 7,
                'group' => 3,
                'distribution' => '2,8,18,32,30,8,2',
                'state' => 3,
                'family' => 1,
                'occurence' => 'Synthétique',
            ],

            [
                'mass' => 258,
                'neutron' => 157,
                'name' => 'Mendélévium',
                'slug' => 'mendelevium',
                'symbol' => 'Md',
                'period' => 7,
                'group' => 3,
                'distribution' => '2,8,18,32,31,8,2',
                'state' => 3,
                'family' => 1,
                'occurence' => 'Synthétique',
            ],

            [
                'mass' => 259,
                'neutron' => 157,
                'name' => 'Nobélium',
                'slug' => 'nobelium',
                'symbol' => 'No',
                'period' => 7,
                'group' => 3,
                'distribution' => '2,8,18,32,32,8,2',
                'state' => 3,
                'family' => 1,
                'occurence' => 'Synthétique',
            ],

            [
                'mass' => 262,
                'neutron' => 159,
                'name' => 'Lawrencium',
                'slug' => 'lawrencium',
                'symbol' => 'Lr',
                'period' => 7,
                'group' => 3,
                'distribution' => '2,8,18,32,32,8,3',
                'state' => 3,
                'family' => 1,
                'occurence' => 'Synthétique',
            ],

            [
                'mass' => 267,
                'neutron' => 163,
                'name' => 'Rutherfordium',
                'slug' => 'rutherfordium',
                'symbol' => 'Rf',
                'period' => 7,
                'group' => 4,
                'distribution' => '2,8,18,32,32,10,2',
                'state' => 3,
                'family' => 8,
                'occurence' => 'Synthétique',
            ],

            [
                'mass' => 268,
                'neutron' => 163,
                'name' => 'Dubnium',
                'slug' => 'dubnium',
                'symbol' => 'Db',
                'period' => 7,
                'group' => 5,
                'distribution' => '2,8,18,32,32,11,2',
                'state' => 3,
                'family' => 8,
                'occurence' => 'Synthétique',
            ],

            [
                'mass' => 271,
                'neutron' => 165,
                'name' => 'Seaborgium',
                'slug' => 'seaborgium',
                'symbol' => 'Sg',
                'period' => 7,
                'group' => 6,
                'distribution' => '2,8,18,32,32,12,2',
                'state' => 3,
                'family' => 8,
                'occurence' => 'Synthétique',
            ],

            [
                'mass' => 272,
                'neutron' => 165,
                'name' => 'Bohrium',
                'slug' => 'bohrium',
                'symbol' => 'Bh',
                'period' => 7,
                'group' => 7,
                'distribution' => '2,8,18,32,32,13,2',
                'state' => 3,
                'family' => 8,
                'occurence' => 'Synthétique',
            ],

            [
                'mass' => 270,
                'neutron' => 162,
                'name' => 'Hassium',
                'slug' => 'hassium',
                'symbol' => 'Hs',
                'period' => 7,
                'group' => 8,
                'distribution' => '2,8,18,32,32,14,2',
                'state' => 3,
                'family' => 8,
                'occurence' => 'Synthétique',
            ],

            [
                'mass' => 276,
                'neutron' => 167,
                'name' => 'Meitnérium',
                'slug' => 'meitnerium',
                'symbol' => 'Mt',
                'period' => 7,
                'group' => 9,
                'distribution' => '2,8,18,32,32,15,2',
                'state' => 3,
                'family' => 11,
                'occurence' => 'Synthétique',
            ],

            [
                'mass' => 281,
                'neutron' => 171,
                'name' => 'Darmstadium',
                'slug' => 'darmstadium',
                'symbol' => 'Ds',
                'period' => 7,
                'group' => 10,
                'distribution' => '2,8,18,32,32,17,1',
                'state' => 3,
                'family' => 11,
                'occurence' => 'Synthétique',
            ],

            [
                'mass' => 280,
                'neutron' => 169,
                'name' => 'Roentgenium',
                'slug' => 'roentgenium',
                'symbol' => 'Rg',
                'period' => 7,
                'group' => 11,
                'distribution' => '2,8,18,32,32,18,1',
                'state' => 3,
                'family' => 11,
                'occurence' => 'Synthétique',
            ],

            [
                'mass' => 285,
                'neutron' => 173,
                'name' => 'Copernicium',
                'slug' => 'copernicium',
                'symbol' => 'Cn',
                'period' => 7,
                'group' => 12,
                'distribution' => '2,8,18,32,32,18,2',
                'state' => 3,
                'family' => 8,
                'occurence' => 'Synthétique',
            ],

            [
                'mass' => 284,
                'neutron' => 171,
                'name' => 'Nihonium',
                'slug' => 'nihonium',
                'symbol' => 'Nh',
                'period' => 7,
                'group' => 13,
                'distribution' => '2,8,18,32,32,18,3',
                'state' => 3,
                'family' => 11,
                'occurence' => 'Synthétique',
            ],

            [
                'mass' => 289,
                'neutron' => 175,
                'name' => 'Flérovium',
                'slug' => 'flerovium',
                'symbol' => 'Fl',
                'period' => 7,
                'group' => 14,
                'distribution' => '2,8,18,32,32,18,4',
                'state' => 3,
                'family' => 11,
                'occurence' => 'Synthétique',
            ],

            [
                'mass' => 288,
                'neutron' => 173,
                'name' => 'Moscovium',
                'slug' => 'moscovium',
                'symbol' => 'Mc',
                'period' => 7,
                'group' => 15,
                'distribution' => '2,8,18,32,32,18,5',
                'state' => 3,
                'family' => 11,
                'occurence' => 'Synthétique',
            ],

            [
                'mass' => 293,
                'neutron' => 177,
                'name' => 'Livermorium',
                'slug' => 'livermorium',
                'symbol' => 'Lv',
                'period' => 7,
                'group' => 16,
                'distribution' => '2,8,18,32,32,18,6',
                'state' => 3,
                'family' => 11,
                'occurence' => 'Synthétique',
            ],

            [
                'mass' => 294,
                'neutron' => 177,
                'name' => 'Tennesse',
                'slug' => 'tennesse',
                'symbol' => 'Ts',
                'period' => 7,
                'group' => 17,
                'distribution' => '2,8,18,32,32,18,7',
                'state' => 3,
                'family' => 11,
                'occurence' => 'Synthétique',
            ],

            [
                'mass' => 294,
                'neutron' => 176,
                'name' => 'Oganesson',
                'slug' => 'oganesson',
                'symbol' => 'Og',
                'period' => 7,
                'group' => 18,
                'distribution' => '2,8,18,32,32,18,8',
                'state' => 3,
                'family' => 11,
                'occurence' => 'Synthétique',
            ],
        ];

        foreach ($periodic_table as $pt) {
            DB::table('elements')->insert([
                'mass' => $pt['mass'],
                'neutron' => $pt['neutron'],
                'name' => $pt['name'],
                'slug' => $pt['slug'],
                'symbol' => $pt['symbol'],
                'period' => $pt['period'],
                'group' => $pt['group'],
                'distribution' => $pt['distribution'],
                'elements_states_id' => $pt['state'],
                'elements_families_id' => $pt['family'],
                'occurence' => $pt['occurence'],
            ]);
        }
    }
}
